HTTP_API_URL: 'https://api-pub.bitfinex.com/v2/'

ERROR_CODE_SUBSCRIPTION_FAILED: 10300
ERROR_CODE_RATE_LIMIT: 11010
INFO_CODE_RECONNECT: 20051
ERROR_CODE_START_MAINTENANCE: 20006

STARTING_YEAR: 1995

REQUEST_DELAY: 1

URL: http://localhost:8086
TOKEN: dq8hhfRh4A8p3UzTxEilJA93pqIgYpybinTS7SM7WHaaKrJJXIZDP45f11NsXNC3pjX0jBQvFYq-iahEjtsYmQ==
BUCKET: crypto
ORGANIZATION: Universidad De Sevilla

pairs:
  - tBTCUSD
  - tIOTUSD
  - tETHUSD
  - tDOTUSD

timeframes:
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
